name: WebSecScan

on:
  schedule:
    - cron: "0 3 * * *"   # daily at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: websecscan
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install WebSecScan
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run scans
        run: |
          mkdir -p reports
          TS=$(date -u +%Y%m%d_%H%M%S)
          while IFS= read -r url; do
            [ -z "$url" ] && continue
            websecscan "$url" --output html --fast || true
            dom=$(echo "$url" | sed 's|https\?://||; s|/||g')
            if [ -f "reports/scan_${dom}.html" ]; then
              mv "reports/scan_${dom}.html" "reports/${TS}_${dom}.html"
            fi
          done < targets.txt
          touch reports/.nojekyll

      - name: Upload artifact (reports)
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ github.run_number }}
          path: reports/

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports
          keep_files: true
